from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer
)
from reportlab.lib.styles import getSampleStyleSheet
from datetime import datetime


def generate_report(data, filename="resume_report.pdf"):
    """
    Generates a PDF report from resume analysis.
    """

    styles = getSampleStyleSheet()

    doc = SimpleDocTemplate(filename)

    story = []

    story.append(Paragraph("<b>AI Resume Analysis Report</b>", styles["Title"]))
    story.append(Spacer(1, 20))

    story.append(Paragraph(f"<b>ATS Score:</b> {data['ats_score']}%", styles["Heading2"]))
    story.append(Spacer(1, 12))

    story.append(Paragraph("<b>Summary</b>", styles["Heading2"]))
    story.append(Paragraph(data["summary"], styles["BodyText"]))
    story.append(Spacer(1, 15))

    sections = [
        ("Skills Found", data["skills_found"]),
        ("Missing Skills", data["missing_skills"]),
        ("Strengths", data["strengths"]),
        ("Weaknesses", data["weaknesses"]),
        ("Suggestions", data["suggestions"])
    ]

    for title, items in sections:
        story.append(Paragraph(f"<b>{title}</b>", styles["Heading2"]))

        if items:
            for item in items:
                story.append(
                    Paragraph(f"• {item}", styles["BodyText"])
                )
        else:
            story.append(
                Paragraph("None", styles["BodyText"])
            )

        story.append(Spacer(1, 12))
        story.append(Spacer(1, 20))

        story.append(
            Paragraph(
                f"<b>Generated on:</b>{datetime.now().strftime('%d %B %Y %I:%M %p')}",
                styles["Italic"]
            )
        )
        story.append(Spacer(1,10))
        story.append(
            Paragraph("Generated by AI Resume Analyzer",
            styles["Heading3"]
            )
            )
    doc.build(story)

    return filename